# Generated by Django 3.2.13 on 2022-05-06 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_type', models.CharField(max_length=32)),
                ('count', models.IntegerField()),
                ('description', models.TextField()),
                ('original_cost', models.FloatField()),
                ('rental_rate', models.FloatField()),
                ('image', models.CharField(max_length=255)),
            ],
        ),
    ]
