# Generated by Django 3.2.13 on 2022-05-06 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='equipment_name',
            field=models.CharField(default=None, max_length=32),
            preserve_default=False,
        ),
    ]
