# Generated by Django 3.2.13 on 2022-05-07 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_equipment_equipment_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentAccessory',
            fields=[
                ('equipment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rentals.equipment')),
            ],
            bases=('rentals.equipment',),
        ),
        migrations.CreateModel(
            name='EquipmentMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.URLField()),
                ('equipment', models.ManyToManyField(to='rentals.Equipment')),
            ],
        ),
    ]
