# Generated by Django 3.2.13 on 2022-05-07 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_equipmentaccessory_equipmentmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentmedia',
            name='name',
            field=models.CharField(default=None, max_length=32),
            preserve_default=False,
        ),
    ]
