# Generated by Django 3.2.13 on 2022-05-07 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_equipmentmedia_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='equipment_name',
            field=models.CharField(max_length=128),
        ),
    ]
