- name: Install specified python requirements
  pip:
    requirements: /tmp/requirements.txt

- name: stat path
  stat: path=/vagrant/main
  register: django_path

- name: startproject
  ansible.builtin.shell: django-admin startproject main
  when: not django_path.stat.exists
  args:
    chdir: /vagrant
