---
- hosts: all
  become: yes
  vars:
    - db_user: django
    - db_password: django
    - db_name: django
  pre_tasks:
    - apt: 
        update_cache: true
        name: "{{ item }}"
      with_items:
        - python3 
        - python3-pip
        - postgresql 
        - postgresql-contrib
        - postgresql-client
        - postgresql-server-dev-10
    
    - name: "Install Python packages"
      pip: "name={{ item }}  state=present"
      with_items:
        - psycopg2-binary

  tasks:
    - name: "Find out if PostgreSQL is initialized"
      ansible.builtin.stat:
        path: "/var/lib/pgsql/data/pg_hba.conf"
      register: postgres_data

    # - name: "Initialize PostgreSQL"
    #   shell: "postgresql-setup initdb"
    #   when: not postgres_data.stat.exists
 
    - name: "Start and enable services"
      service: "name={{ item }} state=started enabled=yes"
      with_items:
        - postgresql

    - name: include db_setup.yaml
      include: db_setup.yaml
  handlers:
    - name: restart postgres
      service: name=postgresql state=restarted