---
- hosts: all
  become: yes
  vars:
    - django_dir: /vagrant
  pre_tasks:
    - apt: 
        update_cache: true
        name: "{{ item }}"
      with_items:
        - python3 
        - python3-pip

  tasks:
    # - name: include db_setup.yaml
    #   include: db_setup.yaml

    - name: include django_setup.yaml
      include: django_setup.yaml

  handlers:
    - name: restart postgres
      service: name=postgresql state=restarted